version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_ADDRESS}:${POSTGRES_PORT}:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data